### ISSUE TITLE
Printer #3 has a serious issue with the nozzle position

### ISSUE THREAD

**Issue by gcl8a** [gcl8a/rice120#3]
The nozzle head on #3 keeps scraping against the left inside of the enclosure. It appears that the limit switch has failed or is missing.

**Comment by wjc86** [comment]
The limit switch is degraded. I compared it to #2's action, and the switch in #2 clicks audibly significantly earlier than # 3. In all likely hood the switch needs replacing, question is will a new switch be calibrated correctly

**Comment by gcl8a** [comment]
That machine should still be under warranty -- it's the one Keith bought. I'll ask him to contact Ultimaker.

**Comment by gcl8a** [comment]
CORRECTION. I looked at it a little closer. The switch was actually working -- I manually pushed it with a pencil and it stopped the head. So I bent the tab out a bit and now the head stops before it hits the wall. 

It still needs a nozzle and an SD card -- I don't have time at the moment -- but when that gets done we can mark this as closed. The table should be re-leveled, too.

**Comment by gcl8a** [comment]
This has been working over the long term, so closing.
