### ISSUE TITLE
Nozzle for Third Printer Missing

### ISSUE THREAD

**Issue by dtkleman** [gcl8a/rice120#7]
The nozzle for the third printer, the one I was soaking in acetone to unclog, has gone missing. It was located in a white bowl covered in black duct tape in the back room. It was on the counter near the Lewin-Land drawer. Please respond if the nozzle is found, or if you know where it is located.

**Comment by gcl8a** [comment]
Oops. My bad. I put it up in a cabinet (the "I2EMS" cabinet). Since the printer is broken, I didn't think about it. I'll make a space in one of the cabinets (likely Cabinet 14 or 15) for printer supplies.
